### ISSUE TITLE
It not run the thin server

### ISSUE THREAD

**Issue by kay54068** [piccagliani/redmine_nikoniko_calendar2#2]
thin start --prefix /redmine -e production
open the web is not work

**Comment by piccagliani** [comment]
I did not consider using redmine in subdirectory...

Fixed in 167d06a

My enviroment: 

<pre>
 Environment:
   Redmine version                          2.1.2.stable
   Ruby version                             1.9.3 (i686-linux)
   Rails version                            3.2.8
   Environment                              development
   Database adapter                         Mysql2
 Redmine plugins:
   redmine_nikoniko_calendar2               0.0.1
</pre>

then,

<pre>
 $ cd /path/to/redmine
 $ bundle list | grep thin
   * thin (1.5.0)
 $ thin start --prefix=/redmine -e development
 >> Using rack adapter
 /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block  in require': iconv will be deprecated in the future, use String#encode instead.
 >> Thin web server (v1.5.0 codename Knife )
 >> Maximum connections set to 1024
 >> Listening on 0.0.0.0:3000, CTRL+C to stop
</pre>

 Works fine for me.
